source 'https://rubygems.org'

gem 'xip', '~> 2.0'

gem 'railties', '~> 6.1'
gem 'activerecord', '~> 6.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Uncomment to enable the Xip Facebook Driver
# gem 'xip-facebook'

# Uncomment to enable the Xip Twilio SMS Driver
# gem 'xip-twilio'

group :development do
  gem 'foreman'
  gem 'listen', '~> 3.3'
end
