name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: [ 2.7, 3.0, jruby-9.2.14.0, truffleruby-head ]
        exclude:
          - { os: windows-latest , ruby: truffleruby-head }

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} - ${{ matrix.ruby }}

    env:
      BUNDLE_GEMFILE: Gemfile
      XIP_ENV: test

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run specs
        if: startsWith(matrix.os, 'windows')
        run: bin/rspec rspec

      - name: Run specs
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        run: bundle exec rspec
        continue-on-error: ${{ startsWith(matrix.ruby, 'truffleruby') }}
