name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019]
        ruby: [ 2.7, 3.0, truffleruby-head ]
        exclude:
          - { os: windows-2019 , ruby: truffleruby-head }

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} - ${{ matrix.ruby }}

    env:
      BUNDLE_GEMFILE: Gemfile
      XIP_ENV: test

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run specs (Windows)
        if: startsWith(matrix.os, 'windows')
        timeout-minutes: 10
        shell: bash
        run: |
          gem install bundler --no-document
          bundle install --jobs 4 --retry 3
          ./bin/rspec

      - name: Run specs
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        timeout-minutes: 10
        run: bundle exec rspec
        continue-on-error: ${{ startsWith(matrix.ruby, 'truffleruby') }}
