name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.5, 2.6, 2.7, 3.0, jruby-9.1.17.0, jruby-9.2.13.0, truffleruby-head ]
    name: ${{ matrix.ruby }}
    env:
      BUNDLE_GEMFILE: .ci.gemfile
    steps:
    - uses: actions/checkout@v2
      if: startsWith(matrix.ruby, 'truffleruby')
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec
      env:
        XIP_ENV: test
      continue-on-error: ${{ startsWith(matrix.ruby, 'truffleruby') }}
